version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cloudkube_postgres
    environment:
      POSTGRES_DB: cloudkube
      POSTGRES_USER: Vovs
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/changelog:/docker-entrypoint-initdb.d
    networks:
      - cloudkube_network

  minio:
    image: minio/minio:latest
    container_name: cloudkube_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - cloudkube_network

  mongo:
    image: mongo:6
    container_name: cloudkube_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: cloudkube
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cloudkube_network

volumes:
  postgres_data:
  minio_data:
  mongo_data:

networks:
  cloudkube_network:
    driver: bridge 