spring:
  profiles:
    active: postgresql, mongodb
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-1.xml
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  redis:
    host: ${REDIS_HOST}
    port: 6379
  data:
    mongodb:
        uri: mongodb://${MONGO_HOST}:27017/user_posts
minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}